# Generated by Django 4.2.5 on 2023-09-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_anime', '0005_anime_image'),
        ('recommandations', '0002_delete_cachedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrice', models.JSONField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_anime.anime')),
            ],
        ),
    ]
