# Generated by Django 4.2.5 on 2023-09-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandations', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similaritymatrix',
            old_name='film',
            new_name='anime',
        ),
    ]
