# Generated by Django 4.2.5 on 2023-09-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_anime', '0003_anime_episodes_anime_favorites_anime_popularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='favorites',
            field=models.CharField(max_length=100),
        ),
    ]
