# Generated by Django 4.2.5 on 2023-09-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_anime', '0004_alter_anime_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_images/'),
        ),
    ]
